version: '3.8'
services:
  api :
    build: ./SkillabApi
    expose:
      - "8000"
    ports:
      - "8000:8000"
  web :
    build: ./SkillabWeb
    expose:
      - "8080"
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
       - ./db.sql:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
    